### ISSUE TITLE
Join us!

### ISSUE THREAD

**Issue by cobexer** [bgrins/DrawWindow#1]
You seem to try to achieve the same thing we try to achieve over at https://github.com/niklasvh/html2canvas .
Join us!

**Comment by bgrins** [comment]
Yes, I have seen that, it is a very nice project - much more complete than this one I think.  There may be some things here that are not yet implemented there, such as text transform: https://github.com/niklasvh/html2canvas/issues/21

**Comment by cobexer** [comment]
Yes thats exactly why i posted this, help us make html2canvas a complete solution for rendering a page onto a canvas element!
